### ISSUE TITLE
docs.rs example has extra #

### ISSUE THREAD

**Issue by jedbrown** [slint-ui/document-features#22]
There is a [comment in the code](https://github.com/slint-ui/document-features/blob/master/lib.rs#L44-L45), but this accommodation in the code affects the example in the documentation:

https://docs.rs/document-features/latest/document_features/index.html#examples

It seems best if the rendered docs could strip out the leading `#`, but a comment at that point would still be an improvement.

**Comment by ogoffart** [comment]
Thanks for filling an issue.
Looks like there was a change in rustdoc at some point.
It used to work in previous versions: https://docs.rs/document-features/0.2.6/document_features/

I wonder how to make it render properly now.

**Comment by ogoffart** [comment]
I fixed that in commit https://github.com/slint-ui/document-features/commit/8d892427c2a6bd62da7e1db7950f83ab600ef397 
Thanks again for reporting the issue.
