### ISSUE TITLE
0.2.9 causes "Parse error while parsing value description: unbalanced source"

### ISSUE THREAD

**Issue by emilk** [slint-ui/document-features#26]
Repro: `cargo install rerun-cli --locked`

See https://github.com/rerun-io/rerun/issues/6865 for details

I can confirm that it worked on 0.2.8

**Comment by ogoffart** [comment]
Sorry about that. 
I have yanked the version of the crate for now.

**Comment by emilk** [comment]
No worries, shit happens! And thanks :)
