### ISSUE TITLE
Add document_enabled_features

### ISSUE THREAD

**Issue by mdrssv** [slint-ui/document-features#27]
Having an function `document_enabled_features` would be an nice addition to display the set of enabled features to the user of an binary application when implementing an `--version` command.

**Comment by ogoffart** [comment]
But sure I really understand what you're asking. What will call this function and what would be the output for example?

**Comment by mdrssv** [comment]
Maybe this could be even realized by exposing an function returning an list of structs like this: 

```rust
pub struct DocumentedFeature {
  pub feature: &'static str,
  pub description: &'static str,
  pub enabled: bool,
}
```

**Comment by ogoffart** [comment]
Note that document_feature is a proc_macro crate. And i'd like it to stay this way. So we can't have functions and types, only macro.

What is the use case you're looking at?
