### ISSUE TITLE
Docs suggests `document-features` as an optional feature

### ISSUE THREAD

**Issue by emilk** [slint-ui/document-features#7]
Hi, and thanks for a great crate!

[The docs](https://docs.rs/document-features) suggests adding this to your `Cargo.toml`:

```toml
## Enable this when building the docs
document-features = { version = "0.2", optional = true }
```

The problem with this is that it breaks `cargo check`:

```
7 | #![doc = document_features::document_features!()]
  |          ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `document_features`
```

I would suggest updating the docs to instead just have

```toml
document-features = "0.2"
```

unless there is some way to get around the `cargo check` issue that I'm not aware of

**Comment by ogoffart** [comment]
The docs suggest also to use `cfg_attr` in that case.

You could use

```rust
#![cfg_attr(feature = "document-features", doc = document_features::document_features!())]
```

If you think the docs are not clear enough feel free to make a suggestion :-)

**Comment by emilk** [comment]
Ah, I didn't read the far, just copy-pasted the first thing I saw :P

I made a PR where I suggest we always use the more verbose `#![cfg_attr(feature = "document-features", doc = document_features::document_features!())]`
